### ISSUE TITLE
Update request 

### ISSUE THREAD

**Issue by Sonopopee** [maasijam/MCVGO#1]
Hello,

First, I want to thank you for tour awesome project.
It can be really useful for me. I plan to build it, but teensy LC are unavailable until 2024...
So, my question is : Can you provide your eagle Cad or kicad files in order I can update your project with teensy 4.0 ?

Many thanks in advance.
Max

**Comment by maasijam** [comment]
Hi Max,
sorry for the late response.
Good news - I've tested it with a Teensy 4.0 and it works. 

Best regards
Tom
